#Joseph Barton
#CPSC 1021-004, F16
#PA-3
#jbarto3

WordFind: WordFind.cpp driver.cpp
			g++ -Wall WordFind.cpp driver.cpp -o WF2

run:	WF2
			./WF2 inputPA3.txt

clean:
			rm WF2
			rm *.o
