#Joseph Barton
#CPSC 1021-004, F16
#PA-2
#jbarto3

Category: category.cpp driver.cpp
			g++ -Wall category.cpp driver.cpp -o Category

run:	Category
			./Category input.txt

clean:
			rm Category
			rm *.o
package:
			tar -cvzf PA2.tar.gz makefile category.h category.cpp driver.cpp
